# .github/workflows/classroom.yml
name: Autograding
on:
  pull_request:
  push:
jobs:
  autograding:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg   # headless matplotlib
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas matplotlib scikit-learn
          fi
      - uses: education/autograding@v1
